export type Config = {
  BRAND: string;
  theme: string;
  tenant: string;
  defaultLocale: 'ru_RU' | 'en_EN';
  supportEmail?: string;
  supportPhone?: string;
  brand_title?: string;
  telephonyEnabled?: boolean;
  depositEnabled?: boolean;
  clientsHasEmail?: boolean;
  defaultPhoneNumber: string;
  clientsHasLoyalty?: boolean;
  hasVIPClients?: boolean;
  userAutoHostessSet?: boolean;
  autoGuestId?: number;
  CI_COMMIT_SHORT_SHA?: string;
  hasRequests: boolean;
  hasMultiLanguage: boolean;
  hasLogo: boolean;
  currency: string;
  hasStatusFiltersInHallScheme: boolean;
  fullCalendarKey: string;
  shiftModule: boolean;
  requestGrid: boolean;
  isPrintAvailable: boolean;
  vipSign: boolean;
  dragAndDrop: boolean;
  HSE_ENABLED: boolean;
  isReportEnabled: boolean;
  newBookingDesign: boolean;
  sortStatusInDashboard: boolean;
  grayConfirmedStatusColor?: boolean;
  bookingWidget: boolean;
  enableShiftIntervalForGrid?: boolean;
};
