import type { Config } from './schema';

export const DEFAULT_CONFIG = {
    BRAND: 'WRF',
    theme: 'wrf',
    tenant: '',
    defaultLocale: 'ru_RU',
    supportEmail: '',
    supportPhone: '',
    brand_title: '',
    telephonyEnabled: false,
    depositEnabled: true,
    clientsHasEmail: true,
    defaultPhoneNumber: '',
    clientsHasLoyalty: true,
    hasVIPClients: true,
    userAutoHostessSet: false,
    autoGuestId: 0,
    CI_COMMIT_SHORT_SHA: 'local-develop',
    hasRequests: true,
    hasMultiLanguage: false,
    hasLogo: true,
    currency: '₽',
    hasStatusFiltersInHallScheme: false,
    fullCalendarKey: '',
    shiftModule: false,
    requestGrid: false,
    isPrintAvailable: false,
    vipSign: false,
    dragAndDrop: true,
    HSE_ENABLED: true,
    isReportEnabled: true,
    newBookingDesign: false,
    sortStatusInDashboard: false,
    grayConfirmedStatusColor: false,
    bookingWidget: false,
    enableShiftIntervalForGrid: false,
} as const satisfies Config['data'];
