import { z } from 'zod';

export const ConfigSchema = z.object({
    data: z.object({
        theme: z.string(),
        tenant: z.string(),
        brand_title: z.string(),
        defaultLocale: z.string(),
        supportEmail: z.string(),
        supportPhone: z.string(),
        telephonyEnabled: z.boolean(),
        depositEnabled: z.boolean(),
        clientsHasEmail: z.boolean(),
        defaultPhoneNumber: z.string(),
        clientsHasLoyalty: z.boolean(),
        hasVIPClients: z.boolean(),
        userAutoHostessSet: z.boolean(),
        autoGuestId: z.number(),
        CI_COMMIT_SHORT_SHA: z.string(),
        hasRequests: z.boolean(),
        hasMultiLanguage: z.boolean(),
        hasLogo: z.boolean(),
        currency: z.string(),
        hasStatusFiltersInHallScheme: z.boolean(),
        fullCalendarKey: z.string(),
        shiftModule: z.boolean(),
        requestGrid: z.boolean(),
        isPrintAvailable: z.boolean(),
        vipSign: z.boolean(),
        dragAndDrop: z.boolean(),
        HSE_ENABLED: z.boolean(),
        isReportEnabled: z.boolean(),
        newBookingDesign: z.boolean(),
        sortStatusInDashboard: z.boolean(),
        grayConfirmedStatusColor: z.boolean(),
        bookingWidget: z.boolean(),
        enableShiftIntervalForGrid: z.boolean(),
    }),
    hostname: z.string(),
    version: z.string(),
});
